// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MqttTest

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
lv_obj_t * ui_homeScreen;
lv_obj_t * ui_Panel1;
void ui_event_MqttConnectSet(lv_event_t * e);
lv_obj_t * ui_MqttConnectSet;
lv_obj_t * ui_Label17;
void ui_event_MqttSubPag(lv_event_t * e);
lv_obj_t * ui_MqttSubPag;
lv_obj_t * ui_Label18;
void ui_event_MqttPubPag(lv_event_t * e);
lv_obj_t * ui_MqttPubPag;
lv_obj_t * ui_Label19;
void ui_event_CleanMQTTMsg(lv_event_t * e);
lv_obj_t * ui_CleanMQTTMsg;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_MqttState;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_MsgNum;
lv_obj_t * ui_reviceMsg;
// CUSTOM VARIABLES


// SCREEN: ui_ConnestScreen
void ui_ConnestScreen_screen_init(void);
void ui_event_ConnestScreen(lv_event_t * e);
lv_obj_t * ui_ConnestScreen;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
void ui_event_MqttConnect(lv_event_t * e);
lv_obj_t * ui_MqttConnect;
lv_obj_t * ui_Label21;
void ui_event_MqttDisconnect(lv_event_t * e);
lv_obj_t * ui_MqttDisconnect;
lv_obj_t * ui_Label22;
void ui_event_MqttServerUrl(lv_event_t * e);
lv_obj_t * ui_MqttServerUrl;
void ui_event_MqttServerPort(lv_event_t * e);
lv_obj_t * ui_MqttServerPort;
void ui_event_MqttUser(lv_event_t * e);
lv_obj_t * ui_MqttUser;
void ui_event_MqttPassword(lv_event_t * e);
lv_obj_t * ui_MqttPassword;
lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES


// SCREEN: ui_PubicScreen
void ui_PubicScreen_screen_init(void);
void ui_event_PubicScreen(lv_event_t * e);
lv_obj_t * ui_PubicScreen;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
void ui_event_MqttTheme(lv_event_t * e);
lv_obj_t * ui_MqttTheme;
void ui_event_MqttPublicMsg(lv_event_t * e);
lv_obj_t * ui_MqttPublicMsg;
lv_obj_t * ui_Label13;
void ui_event_MqttQos(lv_event_t * e);
lv_obj_t * ui_MqttQos;
void ui_event_MqttPublic(lv_event_t * e);
lv_obj_t * ui_MqttPublic;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES


// SCREEN: ui_SubScreen
void ui_SubScreen_screen_init(void);
void ui_event_SubScreen(lv_event_t * e);
lv_obj_t * ui_SubScreen;
lv_obj_t * ui_Label14;
void ui_event_SubscribeTheme(lv_event_t * e);
lv_obj_t * ui_SubscribeTheme;
void ui_event_MqttSubBtn(lv_event_t * e);
lv_obj_t * ui_MqttSubBtn;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Keyboard3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_MqttConnectSet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConnestScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ConnestScreen_screen_init);
    }
}

void ui_event_MqttSubPag(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SubScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SubScreen_screen_init);
    }
}

void ui_event_MqttPubPag(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PubicScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PubicScreen_screen_init);
    }
}

void ui_event_CleanMQTTMsg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_reviceMsg, LV_OBJ_FLAG_CHECKABLE, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        on_clean_ricv_msg(e);
    }
}

void ui_event_ConnestScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homeScreen_screen_init);
    }
}

void ui_event_MqttConnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mqtt_server_connect(e);
    }
}

void ui_event_MqttDisconnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mqtt_server_disconnect(e);
    }
}

void ui_event_MqttServerUrl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        on_clicked_server_set(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_MqttServerUrl);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_MqttServerPort(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        on_clicked_post_set(e);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_MqttServerPort);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_MqttUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        on_clicked_user_set(e);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_MqttUser);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_MqttPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        on_clicked_passwd_set(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_MqttPassword);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_PubicScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homeScreen_screen_init);
    }
}

void ui_event_MqttTheme(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clicked_theme_input(e);
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_keyboard_set_target(ui_Keyboard2,  ui_MqttTheme);
    }
}

void ui_event_MqttPublicMsg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        clicked_mqtt_msg(e);
        _ui_keyboard_set_target(ui_Keyboard2,  ui_MqttPublicMsg);
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_MqttQos(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        mqtt_qos_value_change(e);
    }
}

void ui_event_MqttPublic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        mqtt_publish(e);
    }
}

void ui_event_SubScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homeScreen_screen_init);
    }
}

void ui_event_SubscribeTheme(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sub_theme_input(e);
        _ui_keyboard_set_target(ui_Keyboard3,  ui_SubscribeTheme);
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_MqttSubBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        sub_theme_btn(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_homeScreen_screen_init();
    ui_ConnestScreen_screen_init();
    ui_PubicScreen_screen_init();
    ui_SubScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_homeScreen);
}
