// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MqttTest

#ifndef _MQTTTEST_UI_H
#define _MQTTTEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
extern lv_obj_t * ui_homeScreen;
extern lv_obj_t * ui_Panel1;
void ui_event_MqttConnectSet(lv_event_t * e);
extern lv_obj_t * ui_MqttConnectSet;
extern lv_obj_t * ui_Label17;
void ui_event_MqttSubPag(lv_event_t * e);
extern lv_obj_t * ui_MqttSubPag;
extern lv_obj_t * ui_Label18;
void ui_event_MqttPubPag(lv_event_t * e);
extern lv_obj_t * ui_MqttPubPag;
extern lv_obj_t * ui_Label19;
void ui_event_CleanMQTTMsg(lv_event_t * e);
extern lv_obj_t * ui_CleanMQTTMsg;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_MqttState;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_MsgNum;
extern lv_obj_t * ui_reviceMsg;
// CUSTOM VARIABLES

// SCREEN: ui_ConnestScreen
void ui_ConnestScreen_screen_init(void);
void ui_event_ConnestScreen(lv_event_t * e);
extern lv_obj_t * ui_ConnestScreen;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
void ui_event_MqttConnect(lv_event_t * e);
extern lv_obj_t * ui_MqttConnect;
extern lv_obj_t * ui_Label21;
void ui_event_MqttDisconnect(lv_event_t * e);
extern lv_obj_t * ui_MqttDisconnect;
extern lv_obj_t * ui_Label22;
void ui_event_MqttServerUrl(lv_event_t * e);
extern lv_obj_t * ui_MqttServerUrl;
void ui_event_MqttServerPort(lv_event_t * e);
extern lv_obj_t * ui_MqttServerPort;
void ui_event_MqttUser(lv_event_t * e);
extern lv_obj_t * ui_MqttUser;
void ui_event_MqttPassword(lv_event_t * e);
extern lv_obj_t * ui_MqttPassword;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

// SCREEN: ui_PubicScreen
void ui_PubicScreen_screen_init(void);
void ui_event_PubicScreen(lv_event_t * e);
extern lv_obj_t * ui_PubicScreen;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
void ui_event_MqttTheme(lv_event_t * e);
extern lv_obj_t * ui_MqttTheme;
void ui_event_MqttPublicMsg(lv_event_t * e);
extern lv_obj_t * ui_MqttPublicMsg;
extern lv_obj_t * ui_Label13;
void ui_event_MqttQos(lv_event_t * e);
extern lv_obj_t * ui_MqttQos;
void ui_event_MqttPublic(lv_event_t * e);
extern lv_obj_t * ui_MqttPublic;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES

// SCREEN: ui_SubScreen
void ui_SubScreen_screen_init(void);
void ui_event_SubScreen(lv_event_t * e);
extern lv_obj_t * ui_SubScreen;
extern lv_obj_t * ui_Label14;
void ui_event_SubscribeTheme(lv_event_t * e);
extern lv_obj_t * ui_SubscribeTheme;
void ui_event_MqttSubBtn(lv_event_t * e);
extern lv_obj_t * ui_MqttSubBtn;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Keyboard3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
