// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MqttTest

#include <stdio.h>
#include "task_communication.h"
#include "ui.h"
#include "ui_interface.h"

static uint8_t rest;

void on_clean_ricv_msg(lv_event_t* e) {
  // Your code here
}

void mqtt_server_connect(lv_event_t* e) {
  // Your code here
  printf("Connecting to MQTT server\n");

  char* mqtt_server = lv_textarea_get_text(ui_MqttServerUrl);
  char* mqtt_port = lv_textarea_get_text(ui_MqttServerPort);
  char* mqtt_user = lv_textarea_get_text(ui_MqttUser);
  char* mqtt_passwd = lv_textarea_get_text(ui_MqttPassword);
  if (mqtt_server == NULL || mqtt_port == NULL || mqtt_user == NULL ||
      mqtt_passwd == NULL) {
    lv_label_set_text(ui_MqttState, "MQTT连接失败: 参数不能为空");
    return;
  }

  printf("Connecting to MQTT server: %s:%s with user: %s\n", mqtt_server,
         mqtt_port, mqtt_user);

  rest = ui_mqtt_connect(mqtt_server, atoi(mqtt_port), "mqtt_client", mqtt_user,
                         mqtt_passwd);

  if (rest) {
    // 连接成功
    lv_label_set_text(ui_MqttState, "Connecting");
    // Connect按钮变绿色并禁用
    lv_obj_set_style_bg_color(ui_MqttConnect, lv_color_hex(0x4CAF50),
                              LV_PART_MAIN);
    lv_obj_add_state(ui_MqttConnect, LV_STATE_DISABLED);

    // Disconnect按钮变红并启用
    lv_obj_set_style_bg_color(ui_MqttDisconnect, lv_color_hex(0xF44336),
                              LV_PART_MAIN);
    lv_obj_clear_state(ui_MqttDisconnect, LV_STATE_DISABLED);
  } else {
    // 连接失败
    lv_label_set_text(ui_MqttState, "Disconnected");
  }
}

void mqtt_server_disconnect(lv_event_t* e) {
  // Disconnect按钮变蓝并禁用
  lv_obj_set_style_bg_color(ui_MqttDisconnect, lv_color_hex(0x2196F3),
                            LV_PART_MAIN);
  lv_obj_add_state(ui_MqttDisconnect, LV_STATE_DISABLED);

  // Connect按钮变蓝并启用
  lv_obj_set_style_bg_color(ui_MqttConnect, lv_color_hex(0x2196F3),
                            LV_PART_MAIN);
  lv_obj_clear_state(ui_MqttConnect, LV_STATE_DISABLED);
}

void on_clicked_server_set(lv_event_t* e) {
  // Your code here
}

void on_clicked_post_set(lv_event_t* e) {
  // Your code here
}

void on_clicked_user_set(lv_event_t* e) {
  // Your code here
}

void on_clicked_passwd_set(lv_event_t* e) {
  // Your code here
}

void clicked_theme_input(lv_event_t* e) {
  // Your code here
}

void clicked_mqtt_msg(lv_event_t* e) {
  // Your code here
}

void mqtt_qos_value_change(lv_event_t* e) {
  // Your code here
}

void mqtt_publish(lv_event_t* e) {
  char qos_value[16];  // 获取QOS值的缓冲区
  char* mqtt_theme = lv_textarea_get_text(ui_MqttTheme);
  char* mqtt_msg = lv_textarea_get_text(ui_MqttPublicMsg);
  lv_dropdown_get_selected_str(ui_MqttQos, qos_value, sizeof(qos_value));
  if (mqtt_theme == NULL || mqtt_msg == NULL) {
    lv_label_set_text(ui_MqttState, "MQTT发布失败: 参数不能为空");
    return;
  }
  printf("Publishing MQTT message to theme: %s msg: %s qos: %s\n", mqtt_theme,
         mqtt_msg, qos_value);
}

void sub_theme_input(lv_event_t* e) {
  // Your code here
}

void sub_theme_btn(lv_event_t* e) {
  char* sub_theme = lv_textarea_get_text(ui_SubscribeTheme);
  if (sub_theme == NULL) {
    lv_label_set_text(ui_MqttState, "订阅主题不能为空");
    return;
  }
  printf("Subscribing to theme: %s\n", sub_theme);
}
