// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MqttTest

#include <stdio.h>
#include "task_communication.h"
#include "ui.h"
#include "ui_interface.h"
#include "mqtt_message_display.h"

static uint8_t rest;

void on_clean_ricv_msg(lv_event_t* e) {
   lv_event_code_t event_code = lv_event_get_code(e);
    
    if (event_code == LV_EVENT_CLICKED) {
        mqtt_display_clear();
        mqtt_display_add_system_msg("clear all messages", "INFO");
    }
}

void mqtt_server_connect(lv_event_t* e) {
  
  printf("Connecting to MQTT server\n");

  char* mqtt_server = lv_textarea_get_text(ui_MqttServerUrl);
  char* mqtt_port = lv_textarea_get_text(ui_MqttServerPort);
  char* mqtt_user = lv_textarea_get_text(ui_MqttUser);
  char* mqtt_passwd = lv_textarea_get_text(ui_MqttPassword);
  if (mqtt_server == NULL || mqtt_port == NULL || mqtt_user == NULL ||
      mqtt_passwd == NULL) {
    lv_label_set_text(ui_MqttState, "MQTT连接失败: 参数不能为空");
    return;
  }

  printf("Connecting to MQTT server: %s:%s with user: %s\n", mqtt_server,
         mqtt_port, mqtt_user);

  rest = ui_mqtt_connect(mqtt_server, atoi(mqtt_port), "mqtt_client", mqtt_user,
                         mqtt_passwd);

  /* if (rest) {
    // 连接成功
    lv_label_set_text(ui_MqttState, "Connecting");
    // Connect按钮变绿色并禁用
    lv_obj_set_style_bg_color(ui_MqttConnect, lv_color_hex(0x4CAF50),
                              LV_PART_MAIN);
    lv_obj_add_state(ui_MqttConnect, LV_STATE_DISABLED);

    // Disconnect按钮变红并启用
    lv_obj_set_style_bg_color(ui_MqttDisconnect, lv_color_hex(0xF44336),
                              LV_PART_MAIN);
    lv_obj_clear_state(ui_MqttDisconnect, LV_STATE_DISABLED);
	mqtt_display_add_system_msg("Connecting to MQTT server", "INFO");
  } else {
    // 连接失败
    lv_label_set_text(ui_MqttState, "Disconnected");
	mqtt_display_add_system_msg("Connect to MQTT server failed","err");
  } */
}

void mqtt_server_disconnect(lv_event_t* e) {
  // Disconnect按钮变蓝并禁用
  lv_obj_set_style_bg_color(ui_MqttDisconnect, lv_color_hex(0x2196F3),
                            LV_PART_MAIN);
  lv_obj_add_state(ui_MqttDisconnect, LV_STATE_DISABLED);

  // Connect按钮变蓝并启用
  lv_obj_set_style_bg_color(ui_MqttConnect, lv_color_hex(0x2196F3),
                            LV_PART_MAIN);
  lv_obj_clear_state(ui_MqttConnect, LV_STATE_DISABLED);

  lv_label_set_text(ui_MqttState, "Disconnected");
  mqtt_display_add_system_msg("Disconnected from MQTT server", "INFO");
}

void on_clicked_server_set(lv_event_t* e) {
  // Your code here
}

void on_clicked_post_set(lv_event_t* e) {
  // Your code here
}

void on_clicked_user_set(lv_event_t* e) {
  // Your code here
}

void on_clicked_passwd_set(lv_event_t* e) {
  // Your code here
}

void clicked_theme_input(lv_event_t* e) {
  // Your code here
}

void clicked_mqtt_msg(lv_event_t* e) {
  // Your code here
}

void mqtt_qos_value_change(lv_event_t* e) {
  // Your code here
}

void mqtt_publish(lv_event_t* e) {
  char qos_str[16];  // 获取QOS值的缓冲区
  char* mqtt_theme = lv_textarea_get_text(ui_MqttTheme);
  char* mqtt_msg = lv_textarea_get_text(ui_MqttPublicMsg);
  int qos_num;

  lv_dropdown_get_selected_str(ui_MqttQos, qos_str, sizeof(qos_str));
  if (mqtt_theme == NULL || mqtt_msg == NULL) {
    lv_label_set_text(ui_MqttState, "MQTT发布失败: 参数不能为空");
    return;
  }

  if(sscanf(qos_str, "Qos %d", &qos_num) != 1 || qos_num < 0 || qos_num > 2) {
	lv_label_set_text(ui_MqttState, "MQTT发布失败: Qos值无效");
	return;
  }

  ui_mqtt_publish(mqtt_theme, mqtt_msg, qos_num);
  printf("Publishing MQTT message to theme: %s msg: %s qos: %d\n", mqtt_theme,
         mqtt_msg, qos_num);
  lv_textarea_set_text(ui_MqttTheme, "");
  lv_textarea_set_text(ui_MqttPublicMsg, "");
}

void sub_theme_input(lv_event_t* e) {
  // Your code here
}

void sub_theme_btn(lv_event_t* e) {
  char* sub_theme = lv_textarea_get_text(ui_SubscribeTheme);
  if (sub_theme == NULL) {
    
    return;
  }
  ui_mqtt_subscribe(sub_theme, 0);
  printf("Subscribing to theme: %s\n", sub_theme);
  lv_textarea_set_text(ui_SubscribeTheme, "");
}
