// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MqttTest

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_clean_ricv_msg(lv_event_t * e);
void mqtt_server_connect(lv_event_t * e);
void mqtt_server_disconnect(lv_event_t * e);
void on_clicked_server_set(lv_event_t * e);
void on_clicked_post_set(lv_event_t * e);
void on_clicked_user_set(lv_event_t * e);
void on_clicked_passwd_set(lv_event_t * e);
void clicked_theme_input(lv_event_t * e);
void clicked_mqtt_msg(lv_event_t * e);
void mqtt_qos_value_change(lv_event_t * e);
void mqtt_publish(lv_event_t * e);
void sub_theme_input(lv_event_t * e);
void sub_theme_btn(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
