// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MqttTest

#include "../ui.h"

void ui_ConnestScreen_screen_init(void)
{
    ui_ConnestScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ConnestScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ConnestScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -122);
    lv_obj_set_y(ui_Label6, -92);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Server:");

    ui_Label7 = lv_label_create(ui_ConnestScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -113);
    lv_obj_set_y(ui_Label7, -9);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "User:");

    ui_Label8 = lv_label_create(ui_ConnestScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -114);
    lv_obj_set_y(ui_Label8, -54);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Port:");

    ui_Label9 = lv_label_create(ui_ConnestScreen);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -124);
    lv_obj_set_y(ui_Label9, 37);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Pssword:");

    ui_MqttConnect = lv_btn_create(ui_ConnestScreen);
    lv_obj_set_width(ui_MqttConnect, 103);
    lv_obj_set_height(ui_MqttConnect, 48);
    lv_obj_set_x(ui_MqttConnect, -61);
    lv_obj_set_y(ui_MqttConnect, 88);
    lv_obj_set_align(ui_MqttConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MqttConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MqttConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_MqttConnect);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Connect");

    ui_MqttDisconnect = lv_btn_create(ui_ConnestScreen);
    lv_obj_set_width(ui_MqttDisconnect, 105);
    lv_obj_set_height(ui_MqttDisconnect, 50);
    lv_obj_set_x(ui_MqttDisconnect, 79);
    lv_obj_set_y(ui_MqttDisconnect, 88);
    lv_obj_set_align(ui_MqttDisconnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MqttDisconnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MqttDisconnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_MqttDisconnect);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 2);
    lv_obj_set_y(ui_Label22, -1);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Disconnect");

    ui_MqttServerUrl = lv_textarea_create(ui_ConnestScreen);
    lv_obj_set_width(ui_MqttServerUrl, 235);
    lv_obj_set_height(ui_MqttServerUrl, 38);
    lv_obj_set_x(ui_MqttServerUrl, 30);
    lv_obj_set_y(ui_MqttServerUrl, -93);
    lv_obj_set_align(ui_MqttServerUrl, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_MqttServerUrl, "mqtt.ernestliu.xyz");
    lv_textarea_set_placeholder_text(ui_MqttServerUrl, "Placeholder...");



    ui_MqttServerPort = lv_textarea_create(ui_ConnestScreen);
    lv_obj_set_width(ui_MqttServerPort, 235);
    lv_obj_set_height(ui_MqttServerPort, 38);
    lv_obj_set_x(ui_MqttServerPort, 31);
    lv_obj_set_y(ui_MqttServerPort, -52);
    lv_obj_set_align(ui_MqttServerPort, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_MqttServerPort, "1883");
    lv_textarea_set_placeholder_text(ui_MqttServerPort, "Placeholder...");



    ui_MqttUser = lv_textarea_create(ui_ConnestScreen);
    lv_obj_set_width(ui_MqttUser, 235);
    lv_obj_set_height(ui_MqttUser, 38);
    lv_obj_set_x(ui_MqttUser, 31);
    lv_obj_set_y(ui_MqttUser, -8);
    lv_obj_set_align(ui_MqttUser, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_MqttUser, "Placeholder...");



    ui_MqttPassword = lv_textarea_create(ui_ConnestScreen);
    lv_obj_set_width(ui_MqttPassword, 235);
    lv_obj_set_height(ui_MqttPassword, 38);
    lv_obj_set_x(ui_MqttPassword, 30);
    lv_obj_set_y(ui_MqttPassword, 36);
    lv_obj_set_align(ui_MqttPassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_MqttPassword, "Placeholder...");



    ui_Keyboard1 = lv_keyboard_create(ui_ConnestScreen);
    lv_obj_set_width(ui_Keyboard1, 309);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 56);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_MqttConnect, ui_event_MqttConnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttDisconnect, ui_event_MqttDisconnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttServerUrl, ui_event_MqttServerUrl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttServerPort, ui_event_MqttServerPort, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttUser, ui_event_MqttUser, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttPassword, ui_event_MqttPassword, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_MqttServerUrl);
    lv_obj_add_event_cb(ui_ConnestScreen, ui_event_ConnestScreen, LV_EVENT_ALL, NULL);

}
