// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MqttTest

#include "../ui.h"

void ui_homeScreen_screen_init(void)
{
    ui_homeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_homeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_Panel1, 315);
    lv_obj_set_height(ui_Panel1, 50);
    lv_obj_set_x(ui_Panel1, -2);
    lv_obj_set_y(ui_Panel1, -94);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MqttConnectSet = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_MqttConnectSet, 60);
    lv_obj_set_height(ui_MqttConnectSet, 36);
    lv_obj_set_x(ui_MqttConnectSet, -120);
    lv_obj_set_y(ui_MqttConnectSet, 0);
    lv_obj_set_align(ui_MqttConnectSet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MqttConnectSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MqttConnectSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_MqttConnectSet);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "C");

    ui_MqttSubPag = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_MqttSubPag, 60);
    lv_obj_set_height(ui_MqttSubPag, 36);
    lv_obj_set_x(ui_MqttSubPag, 40);
    lv_obj_set_y(ui_MqttSubPag, -1);
    lv_obj_set_align(ui_MqttSubPag, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MqttSubPag, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MqttSubPag, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_MqttSubPag);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "S");

    ui_MqttPubPag = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_MqttPubPag, 60);
    lv_obj_set_height(ui_MqttPubPag, 36);
    lv_obj_set_x(ui_MqttPubPag, -40);
    lv_obj_set_y(ui_MqttPubPag, 0);
    lv_obj_set_align(ui_MqttPubPag, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MqttPubPag, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MqttPubPag, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_MqttPubPag);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 2);
    lv_obj_set_y(ui_Label19, 0);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "P");

    ui_CleanMQTTMsg = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_CleanMQTTMsg, 60);
    lv_obj_set_height(ui_CleanMQTTMsg, 36);
    lv_obj_set_x(ui_CleanMQTTMsg, 120);
    lv_obj_set_y(ui_CleanMQTTMsg, -1);
    lv_obj_set_align(ui_CleanMQTTMsg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CleanMQTTMsg, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CleanMQTTMsg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_CleanMQTTMsg);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Clean");

    ui_Panel2 = lv_obj_create(ui_homeScreen);
    lv_obj_set_width(ui_Panel2, 310);
    lv_obj_set_height(ui_Panel2, 30);
    lv_obj_set_x(ui_Panel2, -2);
    lv_obj_set_y(ui_Panel2, 101);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -131);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "State:");

    ui_MqttState = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_MqttState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MqttState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MqttState, -64);
    lv_obj_set_y(ui_MqttState, 1);
    lv_obj_set_align(ui_MqttState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MqttState, "Connected");

    ui_Label3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -7);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "|");

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 22);
    lv_obj_set_y(ui_Label4, 1);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Msg:");

    ui_MsgNum = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_MsgNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MsgNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MsgNum, 54);
    lv_obj_set_y(ui_MsgNum, 1);
    lv_obj_set_align(ui_MsgNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MsgNum, "15");

    ui_reviceMsg = lv_textarea_create(ui_homeScreen);
    lv_obj_set_width(ui_reviceMsg, 312);
    lv_obj_set_height(ui_reviceMsg, 147);
    lv_obj_set_x(ui_reviceMsg, -2);
    lv_obj_set_y(ui_reviceMsg, 9);
    lv_obj_set_align(ui_reviceMsg, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_reviceMsg, "Placeholder...");



    lv_obj_add_event_cb(ui_MqttConnectSet, ui_event_MqttConnectSet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttSubPag, ui_event_MqttSubPag, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttPubPag, ui_event_MqttPubPag, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CleanMQTTMsg, ui_event_CleanMQTTMsg, LV_EVENT_ALL, NULL);

}
