// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MqttTest

#include "../ui.h"

void ui_PubicScreen_screen_init(void)
{
    ui_PubicScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PubicScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_PubicScreen);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -119);
    lv_obj_set_y(ui_Label11, -93);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Theme:");

    ui_Label12 = lv_label_create(ui_PubicScreen);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -124);
    lv_obj_set_y(ui_Label12, -51);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Msg:");

    ui_MqttTheme = lv_textarea_create(ui_PubicScreen);
    lv_obj_set_width(ui_MqttTheme, 223);
    lv_obj_set_height(ui_MqttTheme, 39);
    lv_obj_set_x(ui_MqttTheme, 30);
    lv_obj_set_y(ui_MqttTheme, -93);
    lv_obj_set_align(ui_MqttTheme, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_MqttTheme, "Placeholder...");



    ui_MqttPublicMsg = lv_textarea_create(ui_PubicScreen);
    lv_obj_set_width(ui_MqttPublicMsg, 216);
    lv_obj_set_height(ui_MqttPublicMsg, 122);
    lv_obj_set_x(ui_MqttPublicMsg, 29);
    lv_obj_set_y(ui_MqttPublicMsg, -3);
    lv_obj_set_align(ui_MqttPublicMsg, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_MqttPublicMsg, "Placeholder...");



    ui_Label13 = lv_label_create(ui_PubicScreen);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -128);
    lv_obj_set_y(ui_Label13, 88);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Qos:");

    ui_MqttQos = lv_dropdown_create(ui_PubicScreen);
    lv_dropdown_set_options(ui_MqttQos, "Qos 0\nQos 1\nQos 2");
    lv_obj_set_width(ui_MqttQos, 104);
    lv_obj_set_height(ui_MqttQos, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MqttQos, -48);
    lv_obj_set_y(ui_MqttQos, 89);
    lv_obj_set_align(ui_MqttQos, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MqttQos, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_MqttPublic = lv_btn_create(ui_PubicScreen);
    lv_obj_set_width(ui_MqttPublic, 100);
    lv_obj_set_height(ui_MqttPublic, 36);
    lv_obj_set_x(ui_MqttPublic, 85);
    lv_obj_set_y(ui_MqttPublic, 88);
    lv_obj_set_align(ui_MqttPublic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MqttPublic, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MqttPublic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_MqttPublic);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Public");

    ui_Keyboard2 = lv_keyboard_create(ui_PubicScreen);
    lv_obj_set_width(ui_Keyboard2, 314);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, -1);
    lv_obj_set_y(ui_Keyboard2, 57);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_MqttTheme, ui_event_MqttTheme, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttPublicMsg, ui_event_MqttPublicMsg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttQos, ui_event_MqttQos, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttPublic, ui_event_MqttPublic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PubicScreen, ui_event_PubicScreen, LV_EVENT_ALL, NULL);

}
