// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MqttTest

#include "../ui.h"

void ui_SubScreen_screen_init(void)
{
    ui_SubScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SubScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_SubScreen);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -120);
    lv_obj_set_y(ui_Label14, -92);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "theme: ");

    ui_SubscribeTheme = lv_textarea_create(ui_SubScreen);
    lv_obj_set_width(ui_SubscribeTheme, 150);
    lv_obj_set_height(ui_SubscribeTheme, 41);
    lv_obj_set_x(ui_SubscribeTheme, -8);
    lv_obj_set_y(ui_SubscribeTheme, -90);
    lv_obj_set_align(ui_SubscribeTheme, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SubscribeTheme, "Placeholder...");



    ui_MqttSubBtn = lv_btn_create(ui_SubScreen);
    lv_obj_set_width(ui_MqttSubBtn, 78);
    lv_obj_set_height(ui_MqttSubBtn, 39);
    lv_obj_set_x(ui_MqttSubBtn, 113);
    lv_obj_set_y(ui_MqttSubBtn, -91);
    lv_obj_set_align(ui_MqttSubBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MqttSubBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MqttSubBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_MqttSubBtn);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Sub");

    ui_Label16 = lv_label_create(ui_SubScreen);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -93);
    lv_obj_set_y(ui_Label16, -47);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Subscription list:");

    ui_Keyboard3 = lv_keyboard_create(ui_SubScreen);
    lv_obj_set_width(ui_Keyboard3, 314);
    lv_obj_set_height(ui_Keyboard3, 120);
    lv_obj_set_x(ui_Keyboard3, 0);
    lv_obj_set_y(ui_Keyboard3, 55);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_SubscribeTheme, ui_event_SubscribeTheme, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MqttSubBtn, ui_event_MqttSubBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SubScreen, ui_event_SubScreen, LV_EVENT_ALL, NULL);

}
